DROP TABLE IF EXISTS Messages, Team, MessageGroup, User, Institute;

CREATE TABLE Institute (
id INT AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Team(
id INT AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
job VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
pass VARCHAR(50) NOT NULL,
instID INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (instID)
REFERENCES Institute(id)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE User (
id INT AUTO_INCREMENT,
PRIMARY KEY(id)
);

CREATE TABLE MessageGroup (
id INT AUTO_INCREMENT,
instID INT NOT NULL,
userID INT NOT NULL,
archived ENUM('yes', 'no'),
PRIMARY KEY (id),
FOREIGN KEY (instID)
REFERENCES Institute(id)
ON DELETE CASCADE,
FOREIGN KEY (userID)
REFERENCES User(id)
ON DELETE CASCADE
);

CREATE TABLE Messages (
id INT AUTO_INCREMENT,
message TEXT NOT NULL,
datime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
outin ENUM('out', 'in'),
groupid INT NOT NULL,
teamid INT,
PRIMARY KEY (id),
FOREIGN KEY (groupid)
REFERENCES MessageGroup(id)
ON DELETE CASCADE,
FOREIGN KEY (teamid)
REFERENCES Team(id)
);
